### ISSUE TITLE
--file-store deprecated

### ISSUE THREAD

**Issue by julienflack** [flmu/mlflow-tracking-server#10]
mlflow 1.0.0 deprecated --file-store:
https://github.com/mlflow/mlflow/releases

docker image no longer runs given that it pulls in the latest mlflow

**Comment by flmu** [comment]
Thanks for reporting the issue. I will have a look.

**Comment by rblaine95** [comment]
This can be fixed by changing `--file-store $FILE_DIR` to `--backend-store-uri file://${FILE_DIR}` in run.sh

**Comment by flmu** [comment]
#11 solved this issue
