### ISSUE TITLE
Any way I can look into the code that builds the docker image?

### ISSUE THREAD

**Issue by romitjain** [flmu/mlflow-tracking-server#23]

**Comment by flmu** [comment]
Hey @romitjain ,
Have you checked the following scripts?
- https://github.com/flmu/mlflow-tracking-server/blob/master/.travis/docker_push.sh
- https://github.com/flmu/mlflow-tracking-server/blob/master/.travis/docker_script.sh

**Comment by romitjain** [comment]
Thanks, @flmu, that helps. Are there any steps where you are installing sqllite and creating a sqllite db? Can't find that

**Comment by flmu** [comment]
Nope. 
However, I think you could mount a volume in the Docker container that contains the sqllite DB (or simply extend the Docker file). In this case, you can change the `FILE_DIR` parameter that points to the corresponding path of the DB. See [here](https://github.com/flmu/mlflow-tracking-server/blob/master/mlflow_tracking_server/files/run.sh#L16) for more information.

**Comment by romitjain** [comment]
Ahh, I see that I was confused because I was pulling 0.2 and reading code for 0.5. That sqlite db change happened [here](https://github.com/flmu/mlflow-tracking-server/commit/3df3c4a3d56ca9f950361f6388b4d13eb373675d#diff-572b70964224a98678d5e55301fb62b365f808e932253fc1960c394e1f391cf1).

Any chance I can raise a PR to fix this in the README? I tried pushing but gives me 403

**Comment by flmu** [comment]
You need to fork the project. I can recommend [this manual](https://github.com/firstcontributions/first-contributions) for that.

**Comment by romitjain** [comment]
Thanks!
