### ISSUE TITLE
Error when mlflow tries to write to /mlflow folder

### ISSUE THREAD

**Issue by oriolmirosa** [flmu/mlflow-tracking-server#3]
I'm trying to use your image and use the tracking server when I run models from a notebook run through a server spinned by jupyterhub, which runs in a different docker container (I start both with docker-compose). However, although mlflow works correctly and I can see my model runs in the UI, I get an error message when mlflow tries to write the artifact to the `/mlflow` folder:

`PermissionError: [Errno 13] Permission denied: '/mlflow'`

Do you have any idea of how I can get the two containers to play nicely with each other? (sorry if the question is dumb, I'm a complete docker newbie).

**Comment by flmu** [comment]
@oriolmirosa Did you execute your test on a Windows machine? If not, what is your operating system?

**Comment by oriolmirosa** [comment]
Yes, sorry for the lack of details. I'm working on AWS, on a Ubuntu 16.04 EC2 instance.

**Comment by flmu** [comment]
@oriolmirosa 
I found the bug. Currently, the artifact feature can not be used. I will add a separate Docker image to the repo that will serve as an MLFlow client to enable the artifact feature based on AWS S3 and [Minio](https://github.com/minio) (see #4 ).

**Comment by flmu** [comment]
@oriolmirosa I've changed the storage model for the MLFlow Tracking Server. That would probably help you.
https://github.com/flmu/mlflow-tracking-server/blob/master/README.md

Please note that I have changed the Docker image tag from from `0.1.0` to `0.2.0`
